require( "script-lister" )
	.bind( module )( [
		"utility/event-wrapper.js",
		"utility/component.js",
		"utility/page-component.js",
		"utility/resolve-selector.js",
		"utility/layout.js",

		"mixin/utility/blur-mixin.js",
		"mixin/utility/clear-state-mixin.js",
		"mixin/utility/click-mixin.js",
		"mixin/utility/configure-mixin.js",
		"mixin/utility/focus-mixin.js",
		"mixin/utility/placeholder-mixin.js",
		"mixin/utility/show-hide-mixin.js",
		"mixin/utility/size-mixin.js",
		"mixin/utility/state-change-mixin.js",
		"mixin/utility/layout-mixin.js",
		"mixin/utility/hide-first-mixin.js",
		"mixin/utility/component-mixin.js",

		"mixin/basic/control-mixin.js",
		"mixin/basic/icon-mixin.js",
		"mixin/basic/input-mixin.js",
		"mixin/basic/label-mixin.js",
		"mixin/basic/list-mixin.js",
		"mixin/basic/paragraph-mixin.js",

		"mixin/compound/switch-control-mixin.js",
		"mixin/compound/switch-icon-control-mixin.js",
		"mixin/compound/listbar-mixin.js",
		"mixin/compound/tab-list-mixin.js",

		"mixin/configure/headbar-configure.js",
		"mixin/configure/dashbar-configure.js",
		"mixin/configure/opbar-configure.js",

		"mixin/page/content-mixin.js",
		"mixin/page/page-mixin.js",
		"mixin/page/page-traversal-mixin.js",

		"component/basic/control.js",
		"component/basic/icon.js",
		"component/basic/input.js",
		"component/basic/label.js",
		"component/basic/paragraph.js",

		"component/compound/input-label.js",
		"component/compound/text-input.js",
		"component/compound/link.js",
		"component/compound/switch-link.js",
		"component/compound/passphrase-input.js",
		"component/compound/icon-control.js",
		"component/compound/switch-icon-control.js",
		"component/compound/bar.js",
		"component/compound/tab.js",
		"component/compound/icon-tab.js",
		"component/compound/listbar.js",
		"component/compound/tab-list.js",
		"component/compound/headbar.js",
		"component/compound/dashbar.js",
		"component/compound/opbar.js",
 
		"component/page/body.js",
		"component/page/content.js",
		"component/page/footer.js",
		"component/page/header.js",
		"component/page/page.js"
	] );
